services:
  yolo-trainer:
    build: .
    container_name: aetheria_yolo_road
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1  # LA LIGNE MAGIQUE POUR LES LOGS EN TEMPS RÉEL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ipc: host
    command: tail -f /dev/null  # ← Garde le container ouvert SANS lancer train.py
    stdin_open: true
    tty: true